version: '2'
services:
  mongo:
    image: mongo:3.2.4
    container_name: mongo
    ports:
    - 27017:27017
    command: --smallfiles
    
  mongo-init:
    build: ./mongo-init
    container_name: mongo-init
    links:
      - mongo
      
 #mongo-client:
 #   image: mongoclient/mongoclient
 #   container_name: mongo-client
 #   ports:
 #   - 3030:3000
 #   environment:
 #     - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
 #   links:
 #     - mongo

  
  redisdb:
    image: "redis:alpine"
    container_name: redisservice
    hostname: redis
    ports:
     - "6379:6379"

  eureka:
    build:
      context: ./discovery-eureka-service/
    container_name: eureka
    image: ecommerce/discovery:1.0-SNAPSHOT
    #environment:
    #  eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    tty: false
    ports:
      - 8761:8761

  zipkin:
    build:
      context: ./zipkin-service/
    container_name: zipkin-service
    image: zipkinservice:1.0-SNAPSHOT
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
    tty: false
    ports:
      - 9411:9411

  productsservice:
    image: productsservice:1.0-SNAPSHOT
    container_name: products-service
    depends_on:
      - mongo
      - eureka
      #- redisdb
    #links:
    # - redisdb
    ports:
      - 2222:2222
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
 
